- src/go/examples/build_and_test.yaml
- src/helm/examples/package_and_push.yaml
> add example usage for the orbs

- README.md
> BADGES: add badges to the readme for each of the orbs

- src/helm/commands/install.yaml
- src/helm/commands/lint.yaml
- src/helm/commands/package.yaml
- src/helm/examples/package_and_push.yaml
- src/helm/jobs/validate.yaml
- improves on documentation
- suggests a better name for the extra config file, that better reflects it's purpose
> Rename config file and update docs

- src/helm/commands/package.yaml
- parse output from chart test tool
- fix bug with `helm dep up` in helm v2
> Fix chart name detection

- src/go/@orb.yml
This PR updates the code climate orb dependency which is needed for this to function properly.
> Update dependency for code-climate to 0.1.1

- .circleci/config.yml
- src/deploy/@orb.yml
- src/deploy/examples/build_with_params.yaml
- src/deploy/executors/default.yaml
- src/deploy/jobs/jenkins_build_with_parameters.yaml
New orb for managing deploys at travel audience 
> Deploy orb

- src/helm/commands/package.yaml
`package` command will now take environment variable from context and break it down to add as private helm repos.
> Add helm repo from context

- README.md
adds a helpful badge to the readme to know which version of the orb is available
> DEPLOY: add badge to the readme

- src/go/commands/make-gen.yaml
- src/go/jobs/protobuf_eval.yaml
This PR adds parameter for the protoc version
> protoc version

- src/go/commands/make-gen.yaml
Fixes an issue with getting dependencies needed by the code generation step.
> Fix go get newline

- src/scala/commands/compile.yaml
- src/scala/commands/test.yaml
- src/scala/executors/scala.yaml
- src/scala/jobs/test_and_compile.yaml
In the scala compile/assembly config the submodule to assembly is hardcoded to `streaming`.
This PR parametrizes the submodule.
> Parameterize submodule in scala assembly

- src/deploy/jobs/dag_gitops_deploy.yaml
Sometimes during gitops dag cd nothing will change so we should allow empty commits.
> Allow empty commits

- src/go/jobs/build.yaml
Allow enabling of `CGO_ENABLED` on `go build`
> Add cgo option to go build

- src/deploy/jobs/dag_gitops_deploy.yaml
The sed to replace docker tag is not working as it should. This small change will fix it. 
> Fix bug on sed

- src/docker/jobs/build_and_push.yaml
- src/docker/jobs/docker_git_tag.yaml
- src/docker/jobs/docker_scan.yaml
Use environment variable to specify the docker registry
> Use environment variable for docker registry.

- src/docker/jobs/build_and_push.yaml
This gives an option to add `--build-arg` to docker build
> add build args option

- .circleci/config.yml
The new circleci orb offers a solution for Github Quota issues by removing redundant update checks.
> update circleci orb

- src/deploy/examples/push_to_dag_cd_test_branch.yaml
- src/deploy/jobs/push_to_dag_cd_test_branch.yaml
Add an ability to deploy a test branch into staging to confirm changes in DAG before release a new DAG version
> Add a job to deploy dag to staging

- src/deploy/jobs/push_to_dag_cd_test_branch.yaml
Adjust `push_to_dag_cd_test_barnch` to work with PRs only
> Test DAG only on PRs

- src/deploy/jobs/push_to_dag_cd_test_branch.yaml
- use SHA as docker tag to avoid pulling issues.
> Fixed passed env var

- src/docker/@orb.yml
- src/docker/jobs/build_and_push.yaml
Allow to set docker context to properly build docker inside different folders
> add docker context option

- src/go/commands/make-gen.yaml
In the last PR I just removed the mockery line and deleted the "go get -u". I added it now.
> re-added go get -u command which I accidentally deleted

- src/docker/jobs/build_and_push.yaml
- Provide proper docker hub authentication
- Make extra args parameter optional on docker build
This PR doesn't really require any change from orb users - so it will be applied as a patch version.
> Add docker hub credentials also

- src/docker/jobs/build_and_push.yaml
Move from nexus registry to gcr as default docker registry
> Use GCR as default

- src/docker/jobs/docker_git_tag.yaml
- src/docker/jobs/docker_scan.yaml
Allow to perform git tag push using GCR as default
Allow to perform vulnerability scan using GCR as default
> Fix defaults for other docker commands

- src/code-climate/commands/install.yaml
To 0.9.0. The file format issue was not related to the uploader version:
https://github.com/codeclimate/test-reporter/issues/449
> Bump codeclimate uploader

- src/helm/commands/package.yaml
> Fix helm deletion

- src/helm/commands/lint.yaml
Similar to #67 but for helm validation
> Fix Helm Validation

- src/docker/jobs/build_and_push.yaml
> Sync git submodules in docker orb

- src/helm/commands/lint.yaml
> Helm repos in validate

- src/scala/jobs/run_checks.yaml
- src/scala/jobs/static_check.yaml
https://scalacenter.github.io/scalafix/docs/users/installation.html#enforce-in-ci
> (Scala) Fix scalafix flags

- src/scala/jobs/run_checks.yaml
- src/scala/jobs/static_check.yaml
https://gitter.im/scalacenter/scalafix?at=604b5255a3a2f04f1fef0ad9
> (Scala) Try quotes around `scalafixAll --check`.

- src/helm/commands/package.yaml
- src/helm/examples/package_and_push.yaml
This PR adds functionality of whitespace stripping in helm chart version parsing.
- Add whitespace removal to the helm chart version parse.
> Remove whitespace in helm version parsing

- src/docker/jobs/build_and_push.yaml
> Docker git lfs

- src/go/examples/build_and_test.yaml
- src/go/executors/go_executor.yaml
> Upgrade go to 1.16

- src/scala/@orb.yml
- src/scala/jobs/publish.yaml
attempt to fix missing ssh key fingerprints in one of the scala steps
> Scala ssh keys GitHub - quick fix

- src/scala/jobs/publish.yaml
> Fix scala publish
