travelaudience/orbs

src/go/commands/build.yaml, src/go/examples/build_and_test.yaml, src/go/jobs/build.yaml
adds opinionated way to manage `go build` in a single job
=> GO: add logic to go build step that finds all the subdirectories that are needed to build

src/go/jobs/build.yaml
the build failed before. this fixes the use of parent command
=> fix go orb - not sure why CI didn't catch this before merge

src/code-climate/commands/format_coverage.yaml, src/go/commands/make-gen.yaml
This PR adds a new dependency, the github.com/golang/protobuf/protoc-gen-go tool, in order to correctly generate Protobuf. 
This PR also includes a change in the way the code climate reporting tool uses parameters passed in so when empty it doesn't error.
=> Add protoc gen go dep

src/docker/commands/get_change_name.yaml
It fixes the issue with docker push command failing in case branch name contains `/` and a couple of other special characters
=> escape name

src/helm/@orb.yml, src/helm/commands/push.yaml
Make sure helm repo will be reindexed with the new added new chart
=> index helm repo after adding new chart

src/deploy/jobs/jenkins_build_with_parameters.yaml
fixes not using the default env var
=> DEPLOY: add the server name env var for the default

src/deploy/jobs/jenkins_build_with_parameters.yaml
cause the curl call was otherwise broken
=> DEPLOY: fix the env var usage to be correct

src/helm/commands/package.yaml, src/helm/commands/push.yaml, src/helm/jobs/package_and_push.yaml
The chart testing tool doesn't check for changes when "target branch" _(ie: master)_ is the same as the current branch. This means that when a PR is merged into master, any chart changes are not pushed to stable chart repo. 
There's an upstream PR that could make this cleaner, but for now there's two "tracks" for master vs feature branch. 
=> Fix helm package for master branch packaging 

src/docker/jobs/docker_git_tag.yaml
The original threshold wasn't enough for most use cases. It's still an optional param that can be increased on longer running jobs.
=> DOCKER: increase the wait threshold to allow for builds to complete before retagging image

src/helm/commands/package.yaml
adding `set -e` was important, because the package step was failing, but the CircleCI build was successful. See https://support.circleci.com/hc/en-us/articles/115015733328-Tests-fail-but-job-finishes-successfully
The reason for the failure was twofold:
1. The `version-branchname` was an invalid semantic version due to `/` in the version name, so now replacing some special chars
2. the `ct list-changed` was including a debug statement that was triggering packaging of a false chart
=> HELM: packaging was failing, but build was successful

src/go/commands/make-gen.yaml, src/go/jobs/protobuf_eval.yaml
Fixing issue
`cannot use path@version syntax in GOPATH mode`
=> protoc version

src/gcloud/jobs/copy_file.yaml
we got errors in the form of:
```
```
which meant that even though, `only_file_change` was set to `false`, the parameter value was still required, and causing errors
It would probably be better to add more conditionals to check if all the values are provided when they're needed, but instead I think the revision check might need a bigger refactor.
=> disable required check for past revision values

.circleci/config.yml, README.md, src/scala/@orb.yml, src/scala/commands/compile.yaml, src/scala/commands/test.yaml, src/scala/examples/check_and_compile.yaml, src/scala/examples/only_test.yaml, src/scala/executors/scala.yaml, src/scala/executors/scalafmt.yaml, src/scala/jobs/static_check.yaml, src/scala/jobs/test_and_compile.yaml
Providing a new orb for scala development. Currently has the functionality to run static formatting checks, tests with code-climate coverage, and compile a jar (that will be used in docker image)
=> SCALA: add a new orb for building scala jobs

src/deploy/examples/dag_gitops_cd.yaml, src/deploy/executors/github.yaml, src/deploy/jobs/dag_gitops_deploy.yaml
Add Dag GitOps deploy job to allow the use of gitops approach to deploy google composer dags.
=> Add dag gitops deploy

src/python/executors/pylint.yaml, src/python/jobs/pylint.yaml
During `pylint` we need to have the dependencies installed. For that we need to properly install the requirements.txt when running the `pylint` job.
On this PR we are:
- Changing pylint job to a `python/default` executor
- Installing `requirements`
- Allowing to install `requirements` from custom repository
=> Install requirements when running pylint

src/go/commands/staticcheck.yaml, src/go/jobs/checks.yaml
refers to: [RTT-219/bidder (circleci migration)](https://travelaudience.atlassian.net/secure/RapidBoard.jspa?rapidView=88&projectKey=RTT&modal=detail&selectedIssue=RTT-219)
Bidder is full of static check complains which we are adressing later. In order to finish the migration to circleci, we need the option to skip static-analysi like we had on jenkins.
New Parameter `run-static-analysis` added to ta-go/checks. This will be forwarded to 
`staticcheck` and run or don't run static analysis
=> Added parameter to skip staticcheck

src/helm/commands/package.yaml
When a chart is deleted from a repo the diff will present deleted `Chart.yaml` files. This files are being used to actually package charts, so we need to ignore the ones listed as deleted.
=> Fix helm package git dif by hiding deleted files

src/deploy/jobs/dag_gitops_deploy.yaml
The old line would crash if there is no ini file directly at the root of the dag folder in the dag-cd repo. With the multi-dag repo setup an ini file at the root is not required. For example:
https://app.circleci.com/pipelines/github/travelaudience/workflow-bigquery-monitoring/16/workflows/49f278e0-984b-42b4-8a66-69a16245b619/jobs/13
This PR will look for ini files recursively in the <<parameters.dag_name>> folder, and also not crash if there is no ini file at all.
=> Replaced cd + sed by find + sed to support multi-dag folder setup

src/python/jobs/pylint.yaml, src/python/jobs/test.yaml
Fix for python orb to use an addition pip index instead of replace the default one.
=> Replace index-url to extra-index-url

src/scala/commands/compile.yaml, src/scala/executors/scala.yaml
sbt assembly is failing for sub modules with `-` in the name. This PR should fix this.
=> Fix assembly cmd to work for submodule names with '-' inside

src/docker/jobs/build_and_push.yaml, src/docker/jobs/docker_git_tag.yaml, src/docker/jobs/docker_scan.yaml, src/python/jobs/publish.yaml
We decided to use one global env-var for Nexus username and password for all types of artefacts.
!This is a breaking change and require an update of the name of the environment variable on project/organization level on circleci.!
=> Update nexus env vars to use one default for artefacts type.

src/go/commands/make-gen.yaml
This PR removes Mockery from the `make-gen` command since it is not needed and leads to pipelines fail.
The error which happens because of this:
https://app.circleci.com/pipelines/github/travelaudience/ot-locationserv/59/workflows/7b24e0ae-2ef3-4481-a4f9-e75c4a71d50e/jobs/344
=> removed mockery from make-gen

src/helm/commands/package.yaml, src/helm/commands/push.yaml, src/helm/jobs/package_and_push.yaml
Currently the master branch is hardcoded in code when packaging and publishing helm charts. Since, now we can support multiple `main` branches (master, main, wtv) we need to add support to define it as a variable.
=> Allow to setup stable branch for specific chart

src/scala/jobs/run_static_checks.yaml
When coverage is turned off workflow should execute plain `sbt +test`.
=> Fix scala orb when coverage is turned off in publish library workflow.

src/code-climate/commands/install.yaml
The most recent release of the code-climate reporter is now a zipped file, which breaks some of our CI/CD pipelines.
I would prefer to default to a fixed version of the reporter so this doesn't happen again.
=> Set default version to 0.7.0

src/helm/commands/package.yaml
Helm prior to 2.17 are no longer supported as stated here:
https://helm.sh/blog/new-location-stable-incubator-charts/
Since there is no image available with 2.17 version I am adding a hacky solution to fix it for now. 
=> hacky solution to fix obsolete helm version

src/go/jobs/protobuf_eval.yaml
Apparently we still need this.
=> Add back permissions fix

.gitignore, src/scala/jobs/run_static_checks.yaml
For publish scala library worfklow you will be able to inspect coverage report in circleci ui.
=> (Scala) Store coverage results as artifacts in library workflow

src/scala/commands/test.yaml, src/scala/examples/only_test.yaml, src/scala/executors/scala.yaml, src/scala/jobs/compile_only.yaml, src/scala/jobs/static_check.yaml, src/scala/jobs/test_and_compile.yaml
This step should be almost 0s because of caching instead of downloading the jars everytime, coursier cache folder was missing in old orb.
Bumping default scala orb version to 2.13 as well.
=> (Scala) Add coursier jar cache folder and bump default scala version in fat-jar workflows

src/scala/commands/test.yaml, src/scala/jobs/run_tests.yaml, src/scala/jobs/test_and_compile.yaml
- remove `memory_limit_for_heap` and prefer usage of `.sbtopts` in the project root folder so that localhost and CI use the same settings
-  in case of a test failure, you get a better test report (works with CircleCI insights)
- Coverage report can be always published (doesn't depend on the status of tests)
- In case tests or coverage checks fail, all reports will be published and after that, the CI will fail
=> [DET-1058] Upload test/coverage report in case tests/coverageMinimum fails

src/deploy/jobs/push_to_dag_cd_test_branch.yaml
Add normal name instead of having full cmd rendered as a name:
=> Make more readable command deploy to staging

.circleci/config.yml, README.md, src/helm/commands/install.yaml, src/helm/commands/lint.yaml, src/helm/commands/package.yaml, src/helm/examples/package_and_push.yaml, src/helm/executors/helm-tester.yaml
**This is breaking change, removes commands necessary for Helm 2 to run. Changes work only with Helm 3.**
**Finally it will be minor version, which is not following semantic versioning. Why? -> It will enable us to roll this big change out without modification of any yaml files. Sorry for breaking changes for people using Helm 2.**
- Move orb setup from supporting version 2 to Helm 3
- Depreciate the Helm 2 support
- Set Helm version to `v3.5.4`
- Update dependencies for Helm
- Update CircleCI dependencies
- Update `kind`
- Remove `tiller`
- Update default Kubernetes version to `1.17`
=> DEVOPS-1447 Helm 3 migration

src/deploy/commands/replace_image_tag.yaml
This PR fixes the issue with parsing of the `spec.values.image.tag`. The pervious sed depending on the yaml structure could not properly parse the tag.
Also it requires the following yaml structure:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
spec:
...
values:
image:
tag: "TAG_GOES_HERE"
```
=> Fix bug on gitops cd
